# Generated by Django 4.2.1 on 2023-05-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('name', 'branch')},
        ),
    ]
