# Generated by Django 4.2.1 on 2023-05-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammeanresult',
            name='teacher',
        ),
    ]
