# Generated by Django 4.2.1 on 2023-05-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_classes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('branch', 'name')},
        ),
    ]
