# Generated by Django 4.2.1 on 2023-05-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_exammeanresult_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolperformance',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='schoolperformance',
            name='term',
        ),
        migrations.RemoveField(
            model_name='schoolperformance',
            name='year',
        ),
        migrations.RemoveField(
            model_name='streamperformance',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='streamperformance',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='streamperformance',
            name='term',
        ),
        migrations.RemoveField(
            model_name='streamperformance',
            name='year',
        ),
        migrations.RemoveField(
            model_name='teacherperformance',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='teacherperformance',
            name='mean_marks',
        ),
        migrations.RemoveField(
            model_name='teacherperformance',
            name='teacher_subject',
        ),
        migrations.RemoveField(
            model_name='teacherperformance',
            name='term',
        ),
        migrations.RemoveField(
            model_name='teacherperformance',
            name='year',
        ),
        migrations.DeleteModel(
            name='ClassPerformance',
        ),
        migrations.DeleteModel(
            name='SchoolPerformance',
        ),
        migrations.DeleteModel(
            name='StreamPerformance',
        ),
        migrations.DeleteModel(
            name='TeacherPerformance',
        ),
    ]
