# Generated by Django 3.1.1 on 2023-05-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230514_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.branch'),
            preserve_default=False,
        ),
    ]
