# Generated by Django 3.1.1 on 2023-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230514_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='target_marks',
            field=models.IntegerField(default=65),
            preserve_default=False,
        ),
    ]
