# Generated by Django 3.1.1 on 2023-05-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sessionterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.sessionterm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionterm',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
