# Generated by Django 4.2.1 on 2023-05-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_exam_teacher_alter_exam_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
