# Generated by Django 4.2.1 on 2023-05-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_schoolperformance_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.branch'),
            preserve_default=False,
        ),
    ]
