# Generated by Django 4.2.1 on 2023-05-16 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20230515_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionterm',
            old_name='name',
            new_name='term',
        ),
        migrations.RemoveField(
            model_name='exammeanresult',
            name='exam_id',
        ),
        migrations.AddField(
            model_name='exammeanresult',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.exam', verbose_name='Exam Name'),
        ),
    ]
