# Generated by Django 4.2.1 on 2023-05-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_stream_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='branch',
        ),
    ]
