# Generated by Django 3.1.1 on 2023-05-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230514_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.session'),
            preserve_default=False,
        ),
    ]
