# Generated by Django 3.1.1 on 2023-05-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionterm',
            name='name',
            field=models.CharField(choices=[('Term-1', 'Term 1'), ('Term-2', 'Term 2'), ('Term-3', 'Term 3')], max_length=10),
        ),
    ]
