# Generated by Django 4.2.1 on 2023-05-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_stream_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='class_name',
        ),
    ]
