# Generated by Django 4.2.1 on 2023-05-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_exam_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammeanresult',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.staff'),
        ),
    ]
