# Generated by Django 4.2.1 on 2023-05-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_exammeanresult_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exammeanresult',
            unique_together={('exam', 'subject')},
        ),
    ]
