# Generated by Django 4.2.1 on 2023-05-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_customuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
    ]
